server:
  port: 8080

springdoc:
  show-login-endpoint: true
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
    url: jdbc:h2:mem:test-db

  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    user:
      name: admin
      password: 123456

logging:
  level:
    root: info
    com:
      ph:
        dynamic:
          authorization: trace
