server:
  port: 8080

springdoc:
  show-login-endpoint: true
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
    url: jdbc:h2:file:/mnt/samsung-p2/Projects/madive-h2-db/madive-one

  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true